# -*- coding: utf-8 -*-
"""gunicorn.conf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWi4TriIqvSBrCaodSDyuSCGu3yfvCrH
"""

bind = "0.0.0.0:10000"
workers = 3
loglevel = "debug"
accesslog = "-"
errorlog = "-"
timeout = 120  # ✅ タイムアウトを長めに設定