# Generated by Django 5.1.6 on 2025-02-10 17:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='店舗電話番号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='店舗住所')),
                ('corporation_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人名')),
                ('corporation_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='法人電話番号')),
                ('corporation_address', models.TextField(blank=True, null=True, verbose_name='法人所在地')),
                ('representative', models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者名')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='開業日')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='大業種')),
                ('sub_industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='小業種')),
            ],
        ),
        migrations.CreateModel(
            name='EmailScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='送信先メールアドレス')),
                ('subject', models.CharField(max_length=255, verbose_name='メール件名')),
                ('message', models.TextField(verbose_name='メール内容')),
                ('scheduled_time', models.DateTimeField(verbose_name='送信予定日時')),
                ('sent', models.BooleanField(default=False, verbose_name='送信済み')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=100, verbose_name='営業担当者')),
                ('sales_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='営業担当者のメールアドレス')),
                ('activity_date', models.DateTimeField(auto_now_add=True, verbose_name='営業活動日時')),
                ('result', models.CharField(choices=[('再コール', '再コール'), ('追わない', '追わない'), ('見込', '見込'), ('アポ成立', 'アポ成立'), ('受注', '受注'), ('失注', '失注'), ('不通留守', '不通留守'), ('担当不在', '担当不在')], default='見込', max_length=20, verbose_name='営業結果')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('next_action_date', models.DateTimeField(blank=True, null=True, verbose_name='次回営業予定日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleslist.company', verbose_name='企業')),
            ],
        ),
    ]
