# Generated by Django 5.1.6 on 2025-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='corporation_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='法人電話番号'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='店舗電話番号'),
        ),
    ]
