# Generated by Django 5.1.6 on 2025-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0002_alter_company_corporation_phone_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default='未設定'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='corporation_name',
            field=models.CharField(db_index=True, default='未設定', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(db_index=True, default='未設定', max_length=20),
            preserve_default=False,
        ),
    ]
