# Generated by Django 5.1.6 on 2025-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0003_alter_company_address_alter_company_corporation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(db_index=True, default='なし', max_length=20),
        ),
    ]
