# Generated by Django 5.1.6 on 2025-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0004_userprofile_acquired_usage_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='progress',
            field=models.CharField(blank=True, choices=[('発注前', '発注前'), ('後確待ち', '後確待ち'), ('設置待ち', '設置待ち'), ('マッチング待ち', 'マッチング待ち'), ('完了', '完了')], max_length=20, null=True),
        ),
    ]
