# Generated by Django 5.1.6 on 2025-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0005_userprofile_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FAX番号'),
        ),
    ]
