# Generated by Django 5.1.6 on 2025-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0005_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(db_index=True, default='なし', max_length=100),
        ),
    ]
