# Generated by Django 5.1.6 on 2025-08-09 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0006_alter_company_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル（任意）')),
                ('url', models.URLField(verbose_name='画像リンクURL（必須）')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='メモ（任意）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_links', to='saleslist.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
