# Generated by Django 5.1.6 on 2025-03-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0006_alter_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='携帯番号'),
        ),
    ]
