# Generated by Django 5.1.6 on 2025-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0007_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesactivity',
            name='is_decision_maker',
            field=models.BooleanField(db_index=True, default=False, verbose_name='決裁者と会話'),
        ),
    ]
