# Generated by Django 5.1.6 on 2025-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleslist', '0009_alter_company_address_alter_company_corporation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='会社メモ'),
        ),
    ]
